# Generated by Django 4.2.7 on 2023-12-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_booking_category'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE app_car ALTER COLUMN available TYPE SMALLINT USING CASE WHEN available THEN 1 ELSE 0 END;',
            reverse_sql='ALTER TABLE app_car ALTER COLUMN available TYPE BOOLEAN USING CASE WHEN available = 1 THEN TRUE ELSE FALSE END;'
        )
    ]