# Generated by Django 4.2.7 on 2025-04-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_car_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='available',
            field=models.SmallIntegerField(default=0),
        ),
    ]
